### ISSUE TITLE
[1.19.2] The mod does not load properly

### ISSUE THREAD

**Issue by cleakey** [anar4732/acmc#1]
When I installed this mod, I got the following warning message

Warning while loading mods
1 warning has occurred during loading

File acmc-mc1.19.2.jar is not a valid mod file

The forge version is 43.2.8

**Comment by the-ecips** [comment]
Same problem, same forge version.

"File acmc-mc1.19.2.jar is not a valid mod file"

**Comment by anar4732** [comment]
fixed on last 1.19.2 version.
